---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd
  namespace: core
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`carbon.<path:gitops:base#domain>`)
      kind: Rule
      services:
        - name: argocd-server
          port: 443
      middlewares:
        - name: default-headers
          namespace: core