apiVersion: v2
name: prometheus-stack
type: application
version: 0.0.0
dependencies:
  - name: kube-prometheus-stack
    version: 65.6.0
    repository: https://prometheus-community.github.io/helm-charts