apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addon
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/marshallbrain/homelab-gitops.git
        revision: develop
        directories:
          - path: addon/*
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/marshallbrain/homelab-gitops.git
        targetRevision: develop
        path: "{{ .path.path }}"
        plugin:
          env:
            - name: AVP_TYPE
              value: kubernetessecret
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .path.basename }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 16m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true