---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: cert-manager
spec:
  secretName: certificate-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.<path:gitops:base#domain>"
  dnsNames:
  - "<path:gitops:base#domain>"
  - "*.<path:gitops:base#domain>"