---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: <path:gitops:base#email>
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            email: <path:gitops:base#email>
            apiTokenSecretRef:
              name: cloudflare-secret
              key: cloudflare-token
        selector:
          dnsZones:
            - "<path:gitops:base#domain_base>"