---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      name: immich
  template:
    metadata:
      labels:
        name: immich
    spec:
      securityContext:
        # runAsUser: 1200
        # runAsGroup: 1200
        fsGroup: 1200
        supplementalGroups: [1000]
      containers:
        - name: immich-server
          image: "ghcr.io/immich-app/immich-server:v1.120.1"
          env:
            - name: TZ
              value: america/new_york
            - name: REDIS_HOSTNAME
              value: immich-redis-master
            - name: DB_HOSTNAME
              value: immich-postgres-rw
            - name: DB_USERNAME
              value: immich
            - name: DB_DATABASE_NAME
              value: immich
            - name: IMMICH_PORT
              value: "2283"
            - name: IMMICH_IGNORE_MOUNT_CHECK_ERRORS
              value: "true"
          envFrom:
            - secretRef:
                name: immich-db-secret
          ports:
            - name: http
              containerPort: 2283
              protocol: TCP
          volumeMounts:
            - mountPath: /mnt/collections
              name: collections
            - mountPath: /usr/src/app/upload
              name: upload
      volumes:
        - name: collections
          nfs:
            server: <path:gitops:base#domain_nas>
            path: /mnt/<path:gitops:base#nas>/immich/collections
            readOnly: true
        - name: upload
          nfs:
            server: <path:gitops:base#domain_nas>
            path: /mnt/<path:gitops:base#nas>/immich/upload